name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 2.0.0
homepage: https://github.com/jzoom/flutter_swiper

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.17.6 <3.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  flutter_lints: ^2.0.1

flutter:
